"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
setup = "npm install"
run_mode = "concurrent"

[scripts.run.dev]
available_in = [ "local" ]
command = "BROWSER=none PORT=$CONDUCTOR_PORT npm start"
default = true
icon = "play"
